substitutions:
  name: testesp32s3
  friendly_name: testesp32s3
  
  home_assistant_host: http://homeassistant.local:8123


  allowed_characters: " !#%'()+,-./0123456789:;<>?@ABCDEFGHIJKLMNOPQRSTUVWYZ[]_abcdefghijklmnopqrstuvwxyz{|}°²³µ¿ÁÂÄÅÉÖÚßàáâãäåæçèéêëìíîðñòóôõöøùúûüýþāăąćčďĐđēėęěğĮįıļľŁłńňőřśšťũūůűųźŻżŽžơưșțΆΈΌΐΑΒΓΔΕΖΗΘΚΜΝΠΡΣΤΥΦάέήίαβγδεζηθικλμνξοπρςστυφχψωϊόύώАБВГДЕЖЗИКЛМНОПРСТУХЦЧШЪЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёђєіїјљњћאבגדהוזחטיכלםמןנסעפץצקרשת،ءآأإئابةتجحخدذرزسشصضطظعغفقكلمنهوىيٹپچڈکگںھہیےংকচতধনফবযরলশষস়ািু্చయలిెొ్ംഅആഇഈഉഎഓകഗങചജഞടഡണതദധനപഫബഭമയരറലളവശസഹാിീുൂെേൈ്ൺൻർൽൾაბგდევზთილმნოპრსტუფქყშჩცძჭხạảấầẩậắặẹẽếềểệỉịọỏốồổỗộớờởợụủứừửữựỳ—、一上不个中为主乾了些亮人任低佔何作供依侧係個側偵充光入全关冇冷几切到制前動區卧厅厨及口另右吊后吗启吸呀咗哪唔問啟嗎嘅嘛器圍在场執場外多大始安定客室家密寵对將小少左已帘常幫幾库度庫廊廚廳开式後恆感態成我戲戶户房所扇手打执把拔换掉控插摄整斯新明是景暗更最會有未本模機檯櫃欄次正氏水沒没洗活派温測源溫漏潮激濕灯為無煙照熱燈燥物狀玄现現瓦用發的盞目着睡私空窗立笛管節簾籬紅線红罐置聚聲脚腦腳臥色节著行衣解設調請謝警设调走路車车运連遊運過道邊部都量鎖锁門閂閉開關门闭除隱離電震霧面音頂題顏颜風风食餅餵가간감갔강개거게겨결경고공과관그금급기길깥꺼껐꼽나난내네놀누는능니다닫담대더데도동됐되된됨둡드든등디때떤뜨라래러렇렌려로료른를리림링마많명몇모무문물뭐바밝방배변보부불블빨뽑사산상색서설성세센션소쇼수스습시신실싱아안않알았애야어얼업없었에여연열옆오온완외왼요운움워원위으은을음의이인일임입있작잠장재전절정제져조족종주줄중줘지직진짐쪽차창천최추출충치침커컴켜켰쿠크키탁탄태탬터텔통트튼티파팬퍼폰표퓨플핑한함해했행혀현화활후휴힘，？"
  font_glyphsets: "GF_Latin_Core"
  font_family: Figtree

  timer_duration: "5"

  settings:           "\U0000e900" # settings
  thermostat:         "\U0000e901" # thermostat
  lock:               "\U0000e902" # security, alarm
  camera:             "\U0000e903" # camera
  curtains:           "\U0000e904" # curtains
  lights:             "\U0000e905" # lights
  air_conditioner:    "\U0000e906" # air_conditioner
  motion:             "\U0000e907" # motion, presence
  heating:            "\U0000e908" # heating
  alarm_off:          "\U0000e909" # alarm off
  alarm_on:           "\U0000e90a" # alarm on
  ha:                 "\U0000e90b" # home assistant
  color_temp:         "\U0000e90c" # color_temp
  ventilation:        "\U0000e90d" # ventilation
  wifi_25:            "\U0000e91e" # wifi signal from 25% to 1%
  wifi_50:            "\U0000e91f" # wifi signal from 50% to 25%
  wifi_75:            "\U0000e910" # wifi signal from 75% to 50%
  wifi_100:           "\U0000e911" # wifi signal from 100% to 75% or disable
  humidity:           "\U0000e912" # humidity
  co2:                "\U0000e913" # co2
  tvoc:               "\U0000e914" # air quality
  temperature:        "\U0000e915" # temperature
  illumination:       "\U0000e916" # lux
  empty:              "\U0000e917" # placeholder
  vacuum_cleaner:     "\U0000e918" # vacuum cleaner
  logo:               "\U0000e919" # logo
  alarm_home:         "\U000F068A" # alarm home
  alarm_away:         "\U000F0BC4" # alarm away
  alarm_nigt:         "\U000F1828" # armed night
  disarmed:           "\U000F099E" # disarmed
  arming:             "\U000F0565" # arming
  home:               "\U000F1A12" # home 
  tv:                 "\U000F07F4" # tv 
  sound:              "\U000F07C5" # sound
  Battery:            "\U000F0091" # battery
  music:              "\U000F0384" # music
  tools:              "\U000F1322" #tools
  cctv:               "\U000F07AE" #cctv        
  cog:                "\U000F0493" #settings cog  
  voice:              "\U000F05CB" #voice
  screen:             "\U000F0502" #screen settings
  info:               "\U000F1C6F" #info
  scr:                "\U000F0521" #toggle on
  screen_off:         "\U000F0D90" #screen off
  bell:               "\U000F009E" #bell
  stop:               "\U000F04DB" #stop
  sleep:              "\U000F04B2" #sleep
  s_saver:            "\U000F1110" #s_saver
  light_mut:          "\U000F18DD" #light_mut
  alarm_bell:         "\U000F009E" #alarm bell
  clock:              "\U000F0150" #clock
  source:             "\U000F062C" #source
  kubernetes:         "\U000F10FE" #kubernetes
  github:             "\U000F02A4" #github
  angular:            "\U000F06B2" #angular
  radio:              "\U000F0439" #radio
  next:               "\U000F0BB1" #next
  lightbulb:          "\U000F0335"
  aircon:             "\U000F0D43"
  ledstrip:           "\U000F1051"
  package:            "\U000F03D7"
  lumiere:            "\U000F07D6"
  blind:              "\U000F00AC"
  nightlight:         "\U000F1A4C"
  network:            "\U000F1087"
  videocall:          "\U000F036B"
  application:        "\U000F0614"
  gmail:              "\U000F02AB"
  slack:              "\U000F04B1"
  stairs:             "\U000F04CD"
  entry:              "\U000F0E56"
  bedroom:            "\U000F106E"
  radio_active:       "\U000F043C" #radio_active
  music_play:         "\U000F0CB8" #music_play
  heure:              "\U000F1A13" #heure
  meteo:              "\U000F0F30" #meteo
  timer:              "\U000F1923" #timer
  select:             "\U000F04AE" #select
  previous:           "\U000F0664"
  play:               "\U000F03E4"
  pause:              "\U000F03E3"
  refresh:            "\U000F0453"
  play_pause:         "\U000F040E"
  next_track:         "\U000F0662"
  micro_sd:           "\U000F07DC"
  timer_off:          "\U000F13AC"
  timer_play:         "\U000F1AE1"

esphome:
  name: display
  min_version: 2025.2.0
  friendly_name: display
  platformio_options:
    board_build.flash_mode: dio


esp32:
  board: esp32-s3-devkitc-1
  flash_size: 16MB
  cpu_frequency: 240MHz
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP32S3_DEFAULT_CPU_FREQ_240: "y"
      CONFIG_ESP32S3_DATA_CACHE_64KB: "y"
      CONFIG_ESP32S3_DATA_CACHE_LINE_64B: "y"
      CONFIG_ESP32S3_INSTRUCTION_CACHE_32KB: "y" 
      CONFIG_SPIRAM_RODATA: "y"
      CONFIG_SPIRAM_FETCH_INSTRUCTIONS: "y"
      CONFIG_MBEDTLS_EXTERNAL_MEM_ALLOC: "y" 
      CONFIG_MBEDTLS_SSL_PROTO_TLS1_3: "y"

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Testesp32S3 Fallback Hotspot"
    password: ""

captive_portal:
    
psram:
  mode: octal
  speed: 80MHz



external_components:

  - source: github://pr#12312
    components: [font]
    refresh: 1h    
    
  - source:
      type: git
      url: https://github.com/youkorr/lvgl_9.5
      ref:  claude/fix-lvgl-esp32s3-Llg2P #claude/fix-lvgl-image-buttonmatrix-wOKzS
    components: [lvgl, image]
    refresh: always

output:
  - platform: ledc
    pin: GPIO47
    id: backlight_output


light:
  - platform: monochromatic
    id: led
    name: LCD Backlight
    entity_category: config
    output: backlight_output
    restore_mode: ALWAYS_ON
    default_transition_length: 250ms

i2c:
  - id: bus_a
    sda: GPIO08
    scl: GPIO18
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 100kHz

  - id: bus_b
    sda: GPIO41
    scl: GPIO40
    scan: false
    sda_pullup_enabled: true
    scl_pullup_enabled: true
    frequency: 100kHz

touchscreen:
  platform: gt911
  i2c_id: bus_a
  id: gt911_touchscreen
  update_interval: 50ms 
  #reset_pin:
    #number: GPIO3
    #inverted: true
    #ignore_strapping_warning: true
  #update_interval: 50ms
  on_touch:
    - lambda: id(led).turn_on().set_brightness(1.0).perform();


binary_sensor:
  - platform: gpio
    id: top_left_button
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
      ignore_strapping_warning: true

  - platform: gpio
    pin:
      number: GPIO21
    name: "Presence detect"
    disabled_by_default: false
    device_class: "occupancy" 

  - platform: gt911
    id: home_button
    index: 0         

spi:
  clk_pin: 7
  mosi_pin: 6


display:
  - platform: ili9xxx
    id: my_display
    model: S3BOX
    data_rate: 40MHz
    cs_pin: 5
    dc_pin: 4
    reset_pin:
      number: 48
      inverted: true
    update_interval: never
    invert_colors: false 


     

lvgl:
  buffer_size: 100%
  byte_order: little_endian
  displays:
    - my_display  
  touchscreens:
    - gt911_touchscreen     


